### ISSUE TITLE
Vmchecker

### ISSUE THREAD

**Issue by andreiv05** [rosedu/problema-cdl-2018#4]
Salut, am incarcat o solutie scrisa in java pe Vmchecker, dar am o eroare la build. Se pare ca nu este instalat compilatorul de java.
Mesajul de eroare:
make: javac: Command not found
Makefile:8: recipe for target 'Commands.class' failed

**Comment by ionhoria** [comment]
Salut!
Momentan, mașina virtuală utilizată de vmchecker nu dispune de anumite pachete. Soluțiile care au erori de compilare pe vmchecker vor fi rulate încă o dată de noi după modificarea acesteia.
Totodată, rezolvările trimise se vor verifica și manual. Astfel, dacă soluția ta trece testele pe checker-ul local, nu ar trebui să apară alte probleme.
Pentru siguranță, poți menționa in README modul în care trebuie testat programul tău.
